# Generated by Django 4.2.3 on 2023-10-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sem1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
